use FoodShop
go
CREATE TABLE REGISTRATION(
ID nvarchar(50) primary key,
NAME NVARCHAR(20) NOT NULL,
SURNAME NVARCHAR(20) NOT NULL,
LOGIN NVARCHAR(12) NOT NULL,
PASSWORD NVARCHAR(15) NOT NULL
);

INSERT INTO REGISTRATION VALUES ('77', 'Admin', 'Admin', '-', '-')

CREATE TABLE PRODUCTS(
ID INT IDENTITY(1,1) primary key,
TYPE NVARCHAR(50),
NAME NVARCHAR(99),
COUNTS INT,
PRICE FLOAT
);

CREATE TABLE ORDERS(
ID INT IDENTITY(1,1),
USER_ID NVARCHAR(50) foreign key references Registration(ID),
ID_PRODUCT int foreign key references Products(ID),
NAME_PRODUCT NVARCHAR(50),
COUNTS INT,
DATE DATE,
ADRESS NVARCHAR(99),
COMPANY NVARCHAR(99),
NUMBE_ACCOUNT NVARCHAR(99),
SUMM float
);

CREATE TABLE USER_ORDER(
ID INT IDENTITY(1,1),
USER_NAME NVARCHAR(99),
NAME NVARCHAR(99),
COUNTS INT,
DATE DATE,
ADRESS NVARCHAR(99),
COMPANY NVARCHAR(99),
NUMBE_ACCOUNT NVARCHAR(99),
SUMM float
);


